// Types shared by the DSA practice page and the practice API routes.
// Practice is separate from the scored interview: nothing here is graded or stored.

import type { PracticeLanguage, PracticePattern } from "./catalog";

export type Difficulty = "Easy" | "Medium" | "Hard";

export interface PracticeExample {
  input: string;
  output: string;
  explanation?: string;
}

export interface PracticeTestCase {
  input: string;
  expectedOutput: string;
  note?: string;
}

export interface PracticeProblem {
  id: string;
  title: string;
  difficulty: Difficulty;
  topic: string;
  pattern: string;
  /** Where the problem is commonly known from, e.g. "Classic interview problem (LeetCode 1)". */
  knownAs: string;
  statement: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string[];
  examples: PracticeExample[];
  testCases: PracticeTestCase[];
  /** What the interviewer expects from the candidate. */
  expectations: string[];
  /** Starter code for the language the set was generated in. */
  starterCode: string;
  starterLanguage: PracticeLanguage;
}

/** "ai": generated by the model. "built-in": the bundled problem set (mock mode or AI unavailable). */
export type PracticeSource = "ai" | "built-in";

export interface ProblemSetRequest {
  language: PracticeLanguage;
  mode: "random" | "topic";
  topic?: string;
  selections?: { pattern: string; count: 1 | 2 | 3 }[];
  /** Recently seen titles, to avoid repeats. */
  avoidTitles?: string[];
}

export interface ProblemSetReply {
  problems: PracticeProblem[];
  source: PracticeSource;
  notice?: string;
}

export interface PatternsReply {
  topic: string;
  patterns: PracticePattern[];
  source: "catalog" | PracticeSource;
  notice?: string;
}

export type HelpKind = "understand" | "hint" | "solve" | "review" | "ask";

export interface HelpMessage {
  role: "user" | "assistant";
  text: string;
}

export interface HelpRequest {
  kind: HelpKind;
  problem: PracticeProblem;
  language: PracticeLanguage;
  code: string;
  /** For kind "hint": 1, 2 or 3 (each hint reveals a bit more). */
  hintLevel?: number;
  /** For kind "ask": the student's question. */
  question?: string;
  history?: HelpMessage[];
}

export interface HelpSection {
  heading: string;
  body: string;
  code?: string;
}

export interface TestReview {
  input: string;
  verdict: "likely passes" | "likely fails" | "unclear";
  reason: string;
}

export interface HelpReply {
  title: string;
  sections: HelpSection[];
  /** Only for kind "review": reasoning about each test case. The code is never run. */
  testReview?: TestReview[];
  followUps?: string[];
  source: PracticeSource;
  notice?: string;
}

export interface PracticeErrorBody {
  error: { code: string; message: string };
}
